site_name: 'Yuanpeng-Docs'
site_url: https://md.iris-home.net
plugins:
  - search
  - tags:
      tags_file: tags.md
nav:
  - Home: index.md
  - Tools:
    - Collections: tools/collections.md
  - Tags: tags.md
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/library
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.share
    - announce.dismiss
    - content.action.edit
    - content.action.view
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kvieta1990
    - icon: fontawesome/solid/paper-plane
      link: mailto:zyroc1990@gmail.com
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ZhangYuanpeng
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/yuanpeng1990
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/yuanpeng1990/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yuanpeng-zhang-11bb503a/
  generator: false
repo_url: https://github.com/Kvieta1990/mkdocs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Yuanpeng Zhang
